### ISSUE TITLE
code

### ISSUE THREAD

**Issue by XiaoYee** [technion-cs-nlp/LLMsKnow#1]
Thanks for your work. When will you open source the code?

**Comment by OliverLeeXZ** [comment]
Same question.

**Comment by YijuGuo** [comment]
Same question.

**Comment by orgadhadas** [comment]
Hi! Thank you for the interest in our code and paper. The code will be released this week.

**Comment by orgadhadas** [comment]
Hello all,

With some delay - the code is released now!
Please let me know if you experience any bugs and I'll try to accommodate ASAP.
